### PR TITLE
[IMP] Adjusted project requirements to trigger Odoo requirements first.

### PR DESCRIPTION
**Pull request by JevinD**

### CODE REVIEW

**Comment by max3903** [comment]
@ursa-ci Run tests

**Review by max3903 — APPROVED** [review]

**Comment by JevinD** [comment]
@ursa-ci Run tests

**Comment by JevinD** [comment]
@max3903 Is anything needed from me for this PR merge?

**Comment by max3903** [comment]
@JevinD Can you look at fixing the error in Jenkins?

**Comment by JevinD** [comment]
@max3903 I do not know what the issue is. This is a clean copy of Odoo with no customizations.

**Comment by max3903** [comment]
@JevinD Can you try updating it?

**Comment by JevinD** [comment]
@max3903 
Updated and no luck with that failure.

**Comment by max3903** [comment]
@ursa-ci Run tests

**Pull request merged**
